const router = require('koa-router')()
const IndexController = require('./../controllers/index')
const VoteController = require('./../controllers/vote')
const QueryController = require('./../controllers/query')
const HistoryController = require('./../controllers/history')
const BlockInfoController = require('./../controllers/blockInfo')
const TxInfoController = require('./../controllers/txInfo')

router.get('/',IndexController.indexPage)
	.get('/votePage',VoteController.initPage)
	.get('/queryPage',QueryController.initPage)
	.get('/historyPage',HistoryController.initPage)
	.get('/blockInfoPage',BlockInfoController.initPage)
	.get('/txInfoPage',TxInfoController.initPage)
	.post('/voteUser', IndexController.voteUser)
	.get('/getUserVote',IndexController.getUserVote)
	.get('/getUserVoteById',IndexController.getUserVoteById)
	.get('/queryChannelInfo',IndexController.queryChannelInfo)
	.get('/queryBlockById',IndexController.queryBlockById)
	.get('/queryBlockByHash',IndexController.queryBlockByHash)
	.get('/queryBlockByTxId',IndexController.queryBlockByTxId)
	.get('/queryTransaction',IndexController.queryTransaction)

module.exports = router
